question_data = {
    "response_code": 0,
    "results": [
        {
            "type": "multiple",
            "difficulty": "medium",
            "category": "Entertainment: Music",
            "question": "Which country does the electronic music duo &quot;The Knife&quot; originate from?",
            "correct_answer": "Sweden",
            "incorrect_answers": ["Finland", "Denmark", "Norway"],
        },
        {
            "type": "multiple",
            "difficulty": "medium",
            "category": "Entertainment: Books",
            "question": "Which novel by John Grisham was conceived on a road trip to Florida while thinking about stolen books with his wife?",
            "correct_answer": "Camino Island",
            "incorrect_answers": ["Rogue Lawyer", "Gray Mountain", "The Litigators"],
        },
        {
            "type": "multiple",
            "difficulty": "easy",
            "category": "History",
            "question": "What is widely considered to be the oldest civilization known to mankind?",
            "correct_answer": "Sumeria",
            "incorrect_answers": ["Babylon", "Assyria", "Phoenicia"],
        },
        {
            "type": "multiple",
            "difficulty": "easy",
            "category": "Entertainment: Film",
            "question": "Which of the following is not the name of a &quot;Bond Girl&quot;? ",
            "correct_answer": "Vanessa Kensington",
            "incorrect_answers": ["Pam Bouvier", "Mary Goodnight", "Wai Lin"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Entertainment: Music",
            "question": "The Beatles&#039; band name was inspired by the band The Crickets.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "multiple",
            "difficulty": "medium",
            "category": "History",
            "question": "Which of the following is NOT classified as a Semetic language?",
            "correct_answer": "Sumerian",
            "incorrect_answers": ["Maltese", "Akkadian", "Mandaic"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Mythology",
            "question": "In the Greek Mythology, the god of war is called Mars.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Entertainment: Film",
            "question": "Shaquille O&#039;Neal appeared in the 1997 film &quot;Space Jam&quot;.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "multiple",
            "difficulty": "hard",
            "category": "History",
            "question": "The Hagia Sophia was commissioned by which emperor of the Byzantine Empire?",
            "correct_answer": "Justinian I",
            "incorrect_answers": ["Constantine IV", "Arcadius", "Theodosius the Great"],
        },
        {
            "type": "multiple",
            "difficulty": "hard",
            "category": "History",
            "question": "What was the name of the spy ring that helped the United States win the Revolutionary War?",
            "correct_answer": "Culper Ring",
            "incorrect_answers": [
                "New York Spy Ring",
                "Washington&#039;s Spies",
                "Unnamed",
            ],
        },
    ],
}

