data = [
{"name": "Cristiano Ronaldo", "followers": 630, "description": "Footballer", "country": "Portugal"},
{"name": "Lionel Messi", "followers": 500, "description": "Footballer", "country": "Argentina"},
{"name": "Selena Gomez", "followers": 430, "description": "Singer", "country": "USA"},
{"name": "Kylie Jenner", "followers": 400, "description": "Media personality", "country": "USA"},
{"name": "Dwayne Johnson", "followers": 395, "description": "Actor", "country": "USA"},
{"name": "Ariana Grande", "followers": 380, "description": "Singer", "country": "USA"},
{"name": "Kim Kardashian", "followers": 360, "description": "Reality TV personality", "country": "USA"},
{"name": "Beyoncé", "followers": 320, "description": "Singer", "country": "USA"},
{"name": "Taylor Swift", "followers": 330, "description": "Singer", "country": "USA"},
{"name": "Justin Bieber", "followers": 290, "description": "Singer", "country": "Canada"},
{"name": "Kendall Jenner", "followers": 290, "description": "Model", "country": "USA"},
{"name": "Khloé Kardashian", "followers": 310, "description": "Reality TV personality", "country": "USA"},
{"name": "Virat Kohli", "followers": 270, "description": "Cricketer", "country": "India"},
{"name": "Neymar Jr", "followers": 220, "description": "Footballer", "country": "Brazil"},
{"name": "Nicki Minaj", "followers": 230, "description": "Rapper", "country": "USA"},
{"name": "Miley Cyrus", "followers": 210, "description": "Singer", "country": "USA"},
{"name": "Katy Perry", "followers": 200, "description": "Singer", "country": "USA"},
{"name": "Zendaya", "followers": 185, "description": "Actress", "country": "USA"},
{"name": "Kevin Hart", "followers": 180, "description": "Comedian", "country": "USA"},
{"name": "Cardi B", "followers": 170, "description": "Rapper", "country": "USA"},
{"name": "LeBron James", "followers": 160, "description": "Basketball player", "country": "USA"},
{"name": "Shakira", "followers": 155, "description": "Singer", "country": "Colombia"},
{"name": "Jennifer Lopez", "followers": 150, "description": "Singer", "country": "USA"},
{"name": "Demi Lovato", "followers": 150, "description": "Singer", "country": "USA"},
{"name": "Chris Brown", "followers": 140, "description": "Singer", "country": "USA"},
{"name": "Drake", "followers": 145, "description": "Rapper", "country": "Canada"},
{"name": "Vin Diesel", "followers": 100, "description": "Actor", "country": "USA"},
{"name": "Priyanka Chopra", "followers": 90, "description": "Actress", "country": "India"},
{"name": "Shraddha Kapoor", "followers": 85, "description": "Actress", "country": "India"},
{"name": "Deepika Padukone", "followers": 80, "description": "Actress", "country": "India"},
{"name": "Alia Bhatt", "followers": 80, "description": "Actress", "country": "India"},
{"name": "Jacqueline Fernandez", "followers": 70, "description": "Actress", "country": "India"},
{"name": "Anushka Sharma", "followers": 65, "description": "Actress", "country": "India"},
{"name": "Katrina Kaif", "followers": 75, "description": "Actress", "country": "India"},
{"name": "MS Dhoni", "followers": 40, "description": "Cricketer", "country": "India"},
{"name": "Rohit Sharma", "followers": 30, "description": "Cricketer", "country": "India"},
{"name": "Hardik Pandya", "followers": 35, "description": "Cricketer", "country": "India"},
{"name": "KL Rahul", "followers": 20, "description": "Cricketer", "country": "India"},
{"name": "Sachin Tendulkar", "followers": 45, "description": "Cricketer", "country": "India"},
{"name": "Ranveer Singh", "followers": 50, "description": "Actor", "country": "India"},
{"name": "Shah Rukh Khan", "followers": 45, "description": "Actor", "country": "India"},
{"name": "Salman Khan", "followers": 70, "description": "Actor", "country": "India"},
{"name": "Aamir Khan", "followers": 40, "description": "Actor", "country": "India"},
{"name": "Akshay Kumar", "followers": 65, "description": "Actor", "country": "India"},
{"name": "Tom Holland", "followers": 70, "description": "Actor", "country": "UK"},
{"name": "Chris Hemsworth", "followers": 60, "description": "Actor", "country": "Australia"},
{"name": "Robert Downey Jr", "followers": 55, "description": "Actor", "country": "USA"},
{"name": "Zac Efron", "followers": 60, "description": "Actor", "country": "USA"},
{"name": "Will Smith", "followers": 65, "description": "Actor", "country": "USA"},
{"name": "Jason Momoa", "followers": 20, "description": "Actor", "country": "USA"},
{"name": "Gal Gadot", "followers": 100, "description": "Actress", "country": "Israel"},
{"name": "Millie Bobby Brown", "followers": 60, "description": "Actress", "country": "UK"},
{"name": "Emma Watson", "followers": 75, "description": "Actress", "country": "UK"},
{"name": "Emma Stone", "followers": 35, "description": "Actress", "country": "USA"},
{"name": "Scarlett Johansson", "followers": 15, "description": "Actress", "country": "USA"},
{"name": "Lady Gaga", "followers": 75, "description": "Singer", "country": "USA"},
{"name": "Ed Sheeran", "followers": 45, "description": "Singer", "country": "UK"},
{"name": "Billie Eilish", "followers": 110, "description": "Singer", "country": "USA"},
{"name": "Doja Cat", "followers": 30, "description": "Singer", "country": "USA"},
{"name": "Snoop Dogg", "followers": 80, "description": "Rapper", "country": "USA"},
{"name": "50 Cent", "followers": 35, "description": "Rapper", "country": "USA"},
{"name": "Conor McGregor", "followers": 45, "description": "Fighter", "country": "Ireland"},
{"name": "Khabib Nurmagomedov", "followers": 35, "description": "Fighter", "country": "Russia"},
{"name": "Floyd Mayweather", "followers": 30, "description": "Boxer", "country": "USA"},
{"name": "Logan Paul", "followers": 27, "description": "YouTuber", "country": "USA"},
{"name": "Jake Paul", "followers": 25, "description": "YouTuber", "country": "USA"},
{"name": "MrBeast", "followers": 60, "description": "YouTuber", "country": "USA"},
{"name": "PewDiePie", "followers": 20, "description": "YouTuber", "country": "Sweden"},
{"name": "Addison Rae", "followers": 90, "description": "Influencer", "country": "USA"},
{"name": "Charli D'Amelio", "followers": 45, "description": "Influencer", "country": "USA"},
{"name": "Khaby Lame", "followers": 80, "description": "Influencer", "country": "Italy"},
{"name": "Bella Hadid", "followers": 60, "description": "Model", "country": "USA"},
{"name": "Gigi Hadid", "followers": 75, "description": "Model", "country": "USA"},
{"name": "Hailey Bieber", "followers": 50, "description": "Model", "country": "USA"},
{"name": "Cardi B", "followers": 170, "description": "Rapper", "country": "USA"},
{"name": "Bad Bunny", "followers": 50, "description": "Singer", "country": "Puerto Rico"},
{"name": "Maluma", "followers": 60, "description": "Singer", "country": "Colombia"},
{"name": "J Balvin", "followers": 55, "description": "Singer", "country": "Colombia"},
{"name": "Shawn Mendes", "followers": 70, "description": "Singer", "country": "Canada"},
{"name": "Camila Cabello", "followers": 65, "description": "Singer", "country": "USA"},
{"name": "Zayn Malik", "followers": 50, "description": "Singer", "country": "UK"},
{"name": "Louis Tomlinson", "followers": 20, "description": "Singer", "country": "UK"},
{"name": "Niall Horan", "followers": 30, "description": "Singer", "country": "Ireland"},
{"name": "Harry Styles", "followers": 50, "description": "Singer", "country": "UK"},
{"name": "Ananya Panday", "followers": 25, "description": "Actress", "country": "India"},
{"name": "Sara Ali Khan", "followers": 45, "description": "Actress", "country": "India"},
{"name": "Janhvi Kapoor", "followers": 25, "description": "Actress", "country": "India"},
{"name": "Tiger Shroff", "followers": 40, "description": "Actor", "country": "India"},
{"name": "Varun Dhawan", "followers": 45, "description": "Actor", "country": "India"},
{"name": "Ayushmann Khurrana", "followers": 20, "description": "Actor", "country": "India"},
{"name": "Kartik Aaryan", "followers": 35, "description": "Actor", "country": "India"},
{"name": "Parineeti Chopra", "followers": 40, "description": "Actress", "country": "India"}
]