print("Welcome to the tip calculator!")
total_bill = int(input("What was the total bill? $"))
tip = int(input("How much tip would you like to give? 10, 12, or 15? "))
total_people = int(input("How many people to split the bill? "))
each_person_share = round(((total_bill + tip)/total_people),2)
print(f"Each person should pay: ${each_person_share}")